#!/bin/bash

function stripcolor() {
  printf "$result" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g"
}

type=$1
option=$2

repository="/home/minecraft/instances"
syncpath="/home/minecraft/backups/offline_sync"
backuppath="/home/minecraft/backups"
mcpath="/var/mcsnapshot"

case "$1" in
  world)
    if [ -z "$option" ]; then 
      echo "Usage: $0 {world|server|plugins|sync} (subdir)"
      exit 1
    fi
    if [ -d "$mcpath/$option" ]; then
      echo "backing up world: $option"
      /usr/local/bin/mcx "broadcast [AUTO] backing up world: $option"
      /usr/local/bin/mcx save-all
      /usr/local/bin/mcx save-off
      #rsync -vr "$mcpath/$option/" "$syncpath/$option"
      cp "$mcpath/$option/" "$syncpath/" -rf >> /home/minecraft/backup.log
      /usr/local/bin/mcx save-on
    else
      echo "World, $option does not exist"
    fi
    ;;
  server)

    ;;
  plugins)
    echo "backing up server plugins"
    /usr/local/bin/mcx "broadcast [AUTO] backing up server plugins"
    /usr/local/bin/mcx save-all
    /usr/local/bin/mcx save-off
    cp "$mcpath/plugins/" "$syncpath/" -rf >> /home/minecraft/backup.log
    /usr/local/bin/mcx save-on
    ;;
  inventories)
    echo "backing up server plugins"
    /usr/local/bin/mcx "broadcast [AUTO] backing up player inventories"
    /usr/local/bin/mcx save-all
    /usr/local/bin/mcx save-off
    cp "$mcpath/world/players/" "$syncpath/world/" -rf >> /home/minecraft/backup.log
    /usr/local/bin/mcx save-on
    ;;
  sync)
    if [ -z "$option" ]; then 
      echo "syncronizing $syncpath to dev.fourz.org"
      echo "$syncpath/ wizard@dev.fourz.org:$syncpath"
      rsync -rz --delete "$syncpath/" wizard@dev.fourz.org:"$syncpath"
    else
      if [ -d "$syncpath/$option" ]; then
        echo "syncronizing $syncpath/$option to dev.fourz.org"
        rsync -rz --delete "$syncpath/$option" wizard@dev.fourz.org:"$syncpath/$option"
      fi
    fi    
    ;;
  
  *) 
    echo "Usage: $0 {world|server|plugins|sync} (subdir)"
    ;;
esac

exit 0
