#!/bin/bash
for i in "$@"; do
  all="$all$i "
done
ME=`whoami`
COL=green
[[ "$ME" == "rottorz" ]] && COL=dark_purple
[[ "$ME" == "ryanphantom" ]] && COL=aqua

cmd="tellraw @a {'text':'','extra':[{'text':'['},{'text':'$ME@console','color':'$COL'},{'text':'] $all'}]}"
$(dirname $0)/minecraft_svc command "$cmd"